### ISSUE TITLE
Convert multiple MIDI files into single RPP with items and regions?

### ISSUE THREAD

**Issue by d-vyd** [Perlence/rpp#2]
Is it possible to use Perlence to create a RPP file from multiple MIDI files with those files showing up as items with vertical regions? I notice that RPP files store MIDI in ASCII format. The MIDI files I have are binary. I want to be able to program in Python:

insert_MIDI(file1.mid, time=00:00:00)
insert_MIDI(file2.mid, time=00:02:25)
insert_MIDI(file3.mid, time=00:04:50)
create_region(start=00:00:00, end=00:02:25, name="intro")
create_region(start=00:02:25, end=00:04:50, name="part 1")
create_region(start=00:04:50, end=00:06:00, name="chorus")

**Comment by Perlence** [comment]
@d-vyd It's actually a nice idea to have such high-level tools, but this package doesn't provide them at the time, it's basically a parser. Although it will allow you to do it yourself 🙂

**Comment by d-vyd** [comment]
OK. Good to know. Thank you.
________________________________
