### ISSUE TITLE
The rpp.dumps() method does not work properly with multi-level elements

### ISSUE THREAD

**Issue by zcyh147** [Perlence/rpp#4]
Please see the following code
```python
import rpp

fx_chain = '''\
<FXCHAIN_REC
  BYPASS 0 0
  <JS sstillwell/3x3 ""
    0 0 0 0 0 0 240 2400 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  >
  WAK 0 0
  BYPASS 0 0
  <JS loser/5BandJoiner ""
    0 0 0 0 0 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  >
  WAK 0 0
>'''

track = rpp.Element(tag='TRACK', attrib=[], children=fx_chain_formatted)
rpp_root = rpp.Element(tag='REAPER_PROJECT', attrib=['0.1', '6.09/x64', '1594105202'],
                    children=track)
final_result = rpp.dumps(rpp_root)
```

The logic of how the code works is simple, it starts with the fx_chain piece of data to create a project.
But the result of running the code is completely different from what I expect, only the outermost tag is kept in the final rpp.dumps operation, and all the tags in the inner level are ignored, and the result is as follows.
```
<REAPER_PROJECT 0.1 6.09/x64 1594105202
  BYPASS 0 0
  <JS sstillwell/3x3 ""
    0 0 0 0 0 0 240 2400 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  >
  WAK 0 0
  BYPASS 0 0
  <JS loser/5BandJoiner ""
    0 0 0 0 0 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  >
  WAK 0 0
>
```
I wonder if there is something wrong with the recursive logic in your code? THX

**Comment by Perlence** [comment]
Hello @zcyh147! I'm a little confused about `fx_chain_formatted`, is it a string?

**Comment by zcyh147** [comment]
Hi @Perlence ! I'm sorry I wrote the wrong code earlier and forgot a line of code, the correct code is below, where `fx_chain_formatted ` is not a string, it is Elements.
```python
import rpp

fx_chain = '''\
<FXCHAIN_REC
  BYPASS 0 0
  <JS sstillwell/3x3 ""
    0 0 0 0 0 0 240 2400
  >
  WAK 0 0
  BYPASS 0 0
  <JS loser/5BandJoiner ""
    0 0 0 0 0
  >
  WAK 0 0
>'''

fx_chain_formatted = rpp.loads(fx_chain)

track = rpp.Element(tag='TRACK', attrib=[], children=fx_chain_formatted)
rpp_root = rpp.Element( tag='REAPER_PROJECT', attrib=['0.1', '6.09/x64', '1594105202'],
                        children=track )
final_result = rpp.dumps(rpp_root)
```
What I want to do is try to build a REAPER project file from scratch, so I start with a piece of Fx Chain code, first encoding it as Elements object `fx_chain_formatted`.
Then I used it as a chindren object for track and then as a children object for rpp_root, but I got wrong results when I executed dumps on the rpp_root object.

When I print out final_result, I get the following result:
```
<REAPER_PROJECT 0.1 6.09/x64 1594105202
  BYPASS 0 0
  <JS sstillwell/3x3 ""
    0 0 0 0 0 0 240 2400
  >
  WAK 0 0
  BYPASS 0 0
  <JS loser/5BandJoiner ""
    0 0 0 0 0
  >
  WAK 0 0
>
```
Did I misunderstand how to use it? Thank you for your reply!

**Comment by Perlence** [comment]
Passing a list to `children` should work:

```python
...
track = rpp.Element(tag='TRACK', attrib=[], children=[fx_chain_formatted])
rpp_root = rpp.Element( tag='REAPER_PROJECT', attrib=['0.1', '6.09/x64', '1594105202'],
                        children=[track] )
...

**Comment by zcyh147** [comment]
> Passing a list to `children` should work:
> 
> ```python
> ...
> track = rpp.Element(tag='TRACK', attrib=[], children=[fx_chain_formatted])
> rpp_root = rpp.Element( tag='REAPER_PROJECT', attrib=['0.1', '6.09/x64', '1594105202'],
>                         children=[track] )
> ...
> ```

So that's the problem! Thank you very much for your help!!!
