### ISSUE TITLE
Release a new version to pypi

### ISSUE THREAD

**Issue by zcyh147** [Perlence/rpp#5]
I recently switched to Python 3.11 and found that `rpp/rpp/encoder.py` reports an error when executing from collections import Iterable.
After looking through the source code, I found that this fix has been fixed in commit 0ba3583, but it was not released to pypi.
Can you please release a new version, I guess it might be rpp 0.5? Thanks a lot :)

**Comment by Perlence** [comment]
Hey @zcyh147, thanks for noticing! I'll try to release a new version.

**Comment by zcyh147** [comment]
Very much looking forward to it! As someone who likes to develop REAPER automation, your parsing library has helped me a lot!

**Comment by Perlence** [comment]
Thanks, I've released [0.5](https://pypi.org/project/rpp/0.5/).
